services:
  bot:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    # volumes:
    #   - ./logs:/root/logs  # Отключено для облачного деплоя

  # Для будущего расширения с базой данных
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: dailybot
  #     POSTGRES_USER: dailybot
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: